apiVersion: v1
kind: Secret
metadata:
  name: myrandomuniquename
type: Opaque
data:
  api-key: Y015TWFnaWNLZXlJc0FCYW5hbmEK # secret is cMyMagicKeyIsABanana
---
apiVersion: v1
kind: Pod
metadata:
  name: coco-demo-secret
  labels:
    app: coco-demo-secret
  annotations:
    io.katacontainers.config.hypervisor.default_vcpus: "2"
    io.katacontainers.config.hypervisor.default_memory: "4096"
spec:
  runtimeClassName: kata-cc
  containers:
  - name: coco-demo-secret
    image: registry.access.redhat.com/ubi9/ubi:9.3
    command:
    - sleep
    - "36000"
    securityContext:
      privileged: false
      seccompProfile:
        type: RuntimeDefault
    volumeMounts:
    - name: shared-volume
      mountPath: /keys
      readOnly: true
  volumes:
  - name: shared-volume
    secret:
      secretName: myrandomuniquename