apiVersion: v1
kind: Pod
metadata:
  labels:
    app: test-cc-tdx
  name: test-cc-tdx
  namespace: default
spec:
  runtimeClassName: kata-cc
  containers:
  - args:
    - "20000"
    command:
    - sleep
    image: quay.io/rh-ee-chbutler/coredumps:latest
    imagePullPolicy: IfNotPresent
    name: test
